
import { Car, Testimonial, CarCategory } from './types';

export const CARS: Car[] = [
  // HATCHBACKS
  {
    id: 'h1',
    make: 'Maruti Suzuki',
    model: 'Swift',
    variant: 'VXI',
    year: 2020,
    price: 425000,
    category: 'Hatchback',
    fuel: 'Petrol',
    transmission: 'Manual',
    km: 35000,
    ownership: '1st Owner',
    registration: 'GJ-06',
    insurance: 'Valid till Dec 2026',
    color: 'Pearl White',
    engine: '1197 cc',
    seating: 5,
    images: [
      'https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&q=80&w=800'
    ],
    badge: 'Featured',
    features: ['Power Steering', 'Airbags', 'ABS', 'Music System'],
    condition: 'Excellent, Non-accidental, Service records available'
  },
  {
    id: 'h2',
    make: 'Hyundai',
    model: 'i20',
    variant: 'Magna',
    year: 2021,
    price: 650000,
    category: 'Hatchback',
    fuel: 'Petrol',
    transmission: 'Manual',
    km: 28000,
    ownership: '1st Owner',
    registration: 'GJ-01',
    insurance: 'Valid till Nov 2025',
    color: 'Starry Night',
    engine: '1197 cc',
    seating: 5,
    images: ['https://images.unsplash.com/photo-1542281286-9e0a16bb7366?auto=format&fit=crop&q=80&w=800'],
    badge: 'New Arrival',
    features: ['Power Windows', 'Bluetooth', 'Central Locking'],
    condition: 'Mint condition'
  },
  {
    id: 'h3',
    make: 'Tata',
    model: 'Altroz',
    variant: 'XZ',
    year: 2022,
    price: 780000,
    category: 'Hatchback',
    fuel: 'Petrol',
    transmission: 'Manual',
    km: 18000,
    ownership: '1st Owner',
    registration: 'GJ-06',
    insurance: 'Valid till 2027',
    color: 'High Street Gold',
    engine: '1199 cc',
    seating: 5,
    images: ['https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&q=80&w=800'],
    features: ['Alloy Wheels', 'Climate Control', 'Touchscreen'],
    condition: 'Like new'
  },
  // SEDANS
  {
    id: 's1',
    make: 'Honda',
    model: 'City',
    variant: 'V',
    year: 2019,
    price: 825000,
    category: 'Sedan',
    fuel: 'Petrol',
    transmission: 'Manual',
    km: 45000,
    ownership: '2nd Owner',
    registration: 'GJ-05',
    insurance: 'Valid',
    color: 'Radiant Red',
    engine: '1497 cc',
    seating: 5,
    images: ['https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&q=80&w=800'],
    badge: 'Price Drop',
    features: ['Sunroof', 'Leather Seats', 'Cruise Control'],
    condition: 'Well maintained'
  },
  {
    id: 's2',
    make: 'Hyundai',
    model: 'Verna',
    variant: 'SX',
    year: 2021,
    price: 975000,
    category: 'Sedan',
    fuel: 'Diesel',
    transmission: 'Manual',
    km: 32000,
    ownership: '1st Owner',
    registration: 'GJ-06',
    insurance: 'Valid',
    color: 'Polar White',
    engine: '1493 cc',
    seating: 5,
    images: ['https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&q=80&w=800'],
    features: ['Ventilated Seats', 'Wireless Charging', 'Sunroof'],
    condition: 'Showroom condition'
  },
  // SUVs
  {
    id: 'suv1',
    make: 'Maruti Suzuki',
    model: 'Brezza',
    variant: 'ZXI',
    year: 2021,
    price: 890000,
    category: 'Compact SUV',
    fuel: 'Petrol',
    transmission: 'Manual',
    km: 29000,
    ownership: '1st Owner',
    registration: 'GJ-27',
    insurance: 'Valid',
    color: 'Magma Grey',
    engine: '1462 cc',
    seating: 5,
    images: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=800'],
    features: ['SmartPlay Infotainment', 'Reverse Camera', 'Hill Hold Assist'],
    condition: 'Fully serviced'
  },
  {
    id: 'suv2',
    make: 'Hyundai',
    model: 'Venue',
    variant: 'SX',
    year: 2022,
    price: 945000,
    category: 'Compact SUV',
    fuel: 'Petrol',
    transmission: 'Manual',
    km: 22000,
    ownership: '1st Owner',
    registration: 'GJ-06',
    insurance: 'Valid',
    color: 'Titan Grey',
    engine: '998 cc Turbo',
    seating: 5,
    images: ['https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=800'],
    badge: 'New Arrival',
    features: ['Connected Car Tech', 'Projector Lamps'],
    condition: 'Scratchless'
  },
  {
    id: 'suv3',
    make: 'Hyundai',
    model: 'Creta',
    variant: 'SX(O)',
    year: 2023,
    price: 1650000,
    category: 'SUV',
    fuel: 'Diesel',
    transmission: 'Automatic',
    km: 12000,
    ownership: '1st Owner',
    registration: 'GJ-06',
    insurance: 'Full',
    color: 'Phantom Black',
    engine: '1493 cc',
    seating: 5,
    images: ['https://images.unsplash.com/photo-1594562092652-3d76e4c27735?auto=format&fit=crop&q=80&w=800'],
    features: ['Panoramic Sunroof', 'Bose Audio', 'ADAS'],
    condition: 'Brand New'
  },
  // LUXURY
  {
    id: 'lux1',
    make: 'BMW',
    model: '3 Series',
    variant: '320d Luxury Line',
    year: 2018,
    price: 2450000,
    category: 'Luxury',
    fuel: 'Diesel',
    transmission: 'Automatic',
    km: 55000,
    ownership: '2nd Owner',
    registration: 'MH-04',
    insurance: 'Valid',
    color: 'Imperial Blue',
    engine: '1995 cc',
    seating: 5,
    images: ['https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&q=80&w=800'],
    badge: 'Featured',
    features: ['Leather Upholstery', 'Dual Zone Climate', 'Parking Sensors'],
    condition: 'Well maintained, Service at BMW'
  },
  {
    id: 'lux2',
    make: 'Audi',
    model: 'A4',
    variant: 'Technology',
    year: 2021,
    price: 3200000,
    category: 'Luxury',
    fuel: 'Petrol',
    transmission: 'Automatic',
    km: 25000,
    ownership: '1st Owner',
    registration: 'GJ-06',
    insurance: 'Valid',
    color: 'Navarra Blue',
    engine: '1984 cc',
    seating: 5,
    images: ['https://images.unsplash.com/photo-1603584173870-7f3ca994684a?auto=format&fit=crop&q=80&w=800'],
    features: ['Virtual Cockpit', 'Matrix LED', 'Bang & Olufsen'],
    condition: 'Immaculate'
  },
  // ELECTRIC
  {
    id: 'e1',
    make: 'Tata',
    model: 'Nexon EV',
    variant: 'Max XZ+',
    year: 2022,
    price: 1450000,
    category: 'Electric',
    fuel: 'Electric',
    transmission: 'Automatic',
    km: 15000,
    ownership: '1st Owner',
    registration: 'GJ-01',
    insurance: 'Valid',
    color: 'Intensi-Teal',
    engine: '143 hp',
    seating: 5,
    images: ['https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?auto=format&fit=crop&q=80&w=800'],
    badge: 'New Arrival',
    features: ['Fast Charging', 'Connected Car App', 'Regenerative Braking'],
    condition: 'Perfect Battery Health'
  }
];

export const TESTIMONIALS: Testimonial[] = [
  { id: 1, name: 'Raj Patel', text: "Great service! Bought Swift at best price. The team was very helpful with paperwork.", rating: 5 },
  { id: 2, name: 'Priya Sharma', text: "Excellent condition cars. I was skeptical about used cars but Baroda Cars proved me wrong.", rating: 5 },
  { id: 3, name: 'Amit Desai', text: "Very transparent process. No hidden charges. Highly recommended for quality vehicles.", rating: 5 }
];

export const CATEGORIES: CarCategory[] = ['Hatchback', 'Sedan', 'Compact SUV', 'SUV', 'Luxury', 'MUV', 'Electric'];
